name: release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - artifacts-from-commit

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - name: install
        run: |
          npm install -g yarn
          yarn install
      - name: test
        run: yarn test
      - name: build
        run: yarn build
      - name: upload artifacts
        run: |
          git config user.name "BUILD"
          git config user.email "BUILD@GITHUB_ACTIONS"
          rm -rf tmp
          mv dist tmp
          git checkout dist
          rm -rf dist
          mv tmp dist
          git add dist
          git commit -m "Build artifacts"
          BUILD_COMMIT=$(git rev-parse HEAD)
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" dist
          git checkout master
      - name: publish
        run: BUILD_COMMIT=$BUILD_COMMIT CF_API_KEY=${{ secrets.CF_API_KEY }} CF_EMAIL=${{ secrets.CF_EMAIL }} npx wrangler publish --release
