name: release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - debug-github-actions

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - name: install
        run: |
          npm install -g yarn
          yarn install
      - name: test
        run: yarn test
      - name: build
        run: yarn build
      - name: upload artifacts
        run: |
          echo "Configuring github user"
          git config user.name "BUILD"
          git config user.email "BUILD@GITHUB_ACTIONS"
          echo "Creating ./tmp folder"
          rm -rf tmp
          mv dist tmp
          echo "Checking out dist branch"
          git checkout dist
          echo "Replacing build artifacts"
          rm -rf dist
          mv tmp dist
          git add dist
          echo "Comitting build artifacts"
          git commit -m "Build artifacts"
          echo "Pushing build artifacts"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          echo "Resetting workspace to publish"
          git checkout ${{ github.sha }}
      - name: publish
        run: |
          echo "Using build commit $(git rev-parse dist)"
          BUILD_COMMIT=$(git rev-parse dist) CF_API_KEY=${{ secrets.CF_API_KEY }} CF_EMAIL=${{ secrets.CF_EMAIL }} npx wrangler publish --release
